handlers:
  # Handle static files
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$

  # Catch all handler to index.html for client-side routing
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    application_readable: true
    secure: always